[package]
name = "reactor_parser"
version = "0.1.0"
authors = ["Gravechapa <Gravechapa@protonmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
kuchiki = "0.8.0"
regex = "1.3.9"
lazy_static = "1.4.0"
url = "2.1.1"
percent-encoding = "2.1.0"

[profile.dev]
debug = true
opt-level = 0