[package]
name = "reactor_parser"
version = "0.1.0"
authors = ["Gravechapa <Gravechapa@protonmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
kuchiki = "0.8.1"
regex = "1.7.1"
lazy_static = "1.4.0"
url = "2.3.1"
percent-encoding = "2.2.0"

[profile.dev]
debug = true
opt-level = 0
